
# Advanced Python Libraries: NumPy

# <b><u>Chapter 1 Numpy basic</b></u>

In [13]:
#ones(shape)
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#full(shape,value)

filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [15]:
#creating sequence of numbers in numpy
#arrange()
#arrange(statr,stop,step)
import numpy as np
arr = np.arange(1,14,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [16]:
#creating identity matrix
#eye(size)
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Chapter 2: <b><u>Array Properties & Operations</u></b>

In [17]:
#shape.py
#wnen worikng with multi dim data

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.shape)
#2 rows 3 column

(2, 3)


In [18]:
#size.py
#total numbers of elements in array
#to know when we work on big database 

arr = np.array([[10,20,30,7,7,7], [40,50,60,8,8,8]])
print(arr.size)


12


In [40]:
#dimensions

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr_1d .ndim)
print(arr_2d .ndim)
print(arr_3d .ndim)

1
2
3


# 📘 Data Types of Elements
## NumPy Array Properties

In [42]:
arr = np.array([10,20,30.5,40.5,50,60])
print(arr.dtype)

float64


# change data type
## int,str,float

In [46]:
#astype

arr = np.array([1.2,3.4,5.6,4.7])
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)
#array type change float into int


[1 3 5 4]
int64


# Maths Operation

In [48]:
arr =  np.array([10,20,30,40,50])
print(arr + 5)
print(arr * 5)
print(arr - 5)
print(arr * 7)

[15 25 35 45 55]
[ 50 100 150 200 250]
[ 5 15 25 35 45]
[ 70 140 210 280 350]


# aggregation function

In [49]:
#summrize data
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


150
30.0
10
50
14.142135623730951
200.0


#  Summary of Chap 2 
##  SHAPE SIZE DATATYPE ASTYPE MATHS OPERATION AGGREGATION FUNCTION

# 📘 Chapter 3 <b> <u>Indexing & Slicing</u><b>

#### INDEXING = CHOOSE ONE ELEMENTS IN ARRAY
#### SLICING = CHOOSE MULTIPLE ELEMENTS IN ARRAY CHOSE START STOP STEP
#### FANCY INDEXING = CHOOSEMULTIPLE ELEMENTS USING LIST OF INDICES
#### BOOLEN MASKING = GIVE CERTAIN CONDITION AND OPERATE ARRAY 


# <B>INDEXING</B> 
#### ARRAY[INDEX] #1D ARRAY
#### ARRAY[ROW,COLUMN] #2D ARRAY

In [53]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element
print(arr[2])   # Third element
print(arr[-1])  # Last element

10
30
50


# <B> SLICING </B>
#### ARRAY[START,STOP, STEP]
#### ARR[START;END] , START TO END -1 
#### NEGATIVE STEP, -1 REVERSE

In [58]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:5]) # index 1 to 4
print(arr[:4]) # index 0 to 3
print(arr[::2]) # every secound element
print(arr[::-1]) #reverse value

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


# FANCY INDEXING = CHOOSE MULTIPLE ELEMENTS USING LIST OF INDICES

In [59]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[[0,2,4]])


[10 30 50]


# BOOLEN MASKING = GIVE CERTAIN CONDITION AND OPERATE ARRAY (filtering)

In [60]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[arr > 25])

[30 40 50 60]


# <b><u> Reshaping & Manupulating</b></u>
### convert 1D aray into 2D array 
 #### RESHAPING DOES NOT CREAT COPY IT CHANGE ONLY VIEW

In [68]:
arr = np.array([1,2,3,4,5,6,7,8,9])
reshap_arr = arr.reshape(3,3)
print(reshap_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# FLATTING ARRAY
#### 1) RAVEL-->VIEW
#### 2) FLATTEN-->COPY
#### USING WHEN CHANGE MULTI DIMENSIONAL ARRAY INTO 1D ARRAY

In [69]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


# INSERT
#### Array - original array
#### index -
#### value -
#### axis - o row wise in 2d array
####        1 column wise in 2d array

In [72]:
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.insert(arr,2, 100)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [79]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
#insert a new row at index 1 
new_arr_2d = np.insert(arr_2d, 1, [7,8,9], axis=0)
print(new_arr_2d)                      
new_arr_2d = np.insert(arr_2d, 1, [7,8,9])
print(new_arr_2d)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[1 7 8 9 2 3 4 5 6]


# APPEND
#### INSERT VALUE IN END 

In [80]:
arr = np.array([10,20,30,40,50,60])
new_arr = np.append(arr, [70,80,90])
print(new_arr) 

[10 20 30 40 50 60 70 80 90]


# CONCATE
#### JOIN ARRAYS
#### AXIS 0 ROW WISE VERTICAL STACKING
#### AXIS 1 CLOUMN HORIZONTAL STACKING


In [85]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concatenate((arr1, arr2))
print(new_arr)


[1 2 3 4 5 6]


# REMOVING ELEMENTS FROM ARRAY


In [87]:
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.delete(arr, 0)
print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


# STACKING
#### VSTACK ROW WISE
#### HSTACK COLUMN WISE 

In [90]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# SPLITTING
#### EQUAL
#### HORI SPLIT
#### VERTI SPLIT

In [97]:
arr = np.array([10,20,30,40,50,60])
print(np.hsplit(arr, 2))

[array([10, 20, 30]), array([40, 50, 60])]


# <B><U> CHAPTER 4 BROADCASTING & VECTORIZATION</B></U>

In [7]:
import numpy as np
prices = np.array([100,200,300,350,400,4555,5555,4567,3333,2222,11122,555])
discount = 10
final_prices = prices-(prices * discount/100)
print(final_prices)

[   90.    180.    270.    315.    360.   4099.5  4999.5  4110.3  2999.7
  1999.8 10009.8   499.5]


### single value brodcasting

In [9]:
arr = np.array([100,200,300])

result = arr * 2
print (result)

[200 400 600]


## BROADCASTING FOR 1D AND 2D ARRAY

In [12]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])

result = matrix * vector
print(result)

[[ 10  40  90]
 [ 40 100 180]]


## <u>VECTORIZATION</u>

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

result = arr1 * arr2
print(result)

[ 6 14 24 36 50]


# <b><u>CHAPTER 6 Handling Missing & Special Values</b></u>

### bulit in function
####  NAN NOT A NUMBER
#### NP.ISNAN

In [8]:
arr = np.array([1, 2, np.nan, 4,np.nan, 6])

print(np.isnan(arr))

# not compair directly
 

[False False  True False  True False]
